### ISSUE TITLE
Cannot start from sbt

### ISSUE THREAD

**Issue by ghost** [codeoverflow-org/chatoverflow#112] opened 2019-08-09 20:46 UTC
### Description
When starting over `sbt run` plugin initialization fails due to a class not found error

### How to reproduce
Execute `sbt run` from a command line

### Error Log 

```
0    22:35:13.917 [run-main-0] INFO  chatoverflow.ChatOverflow  - Minzig!
1    22:35:13.918 [run-main-0] DEBUG chatoverflow.ChatOverflow  - Starting Chat Overflow Framework. API Version is '2.0'. For more information and updates, please visit: http://codeoverflow.org
1    22:35:13.918 [run-main-0] DEBUG chatoverflow.ChatOverflow  - Initialization started.
1    22:35:13.918 [run-main-0] DEBUG chatoverflow.ChatOverflow  - Enabling framework security policy.
1    22:35:13.918 [run-main-0] DEBUG chatoverflow.ChatOverflow  - Starting plugin framework.
12   22:35:13.929 [run-main-0] INFO  framework.PluginFramework  - Found 3 new plugins.
13   22:35:13.930 [run-main-0] INFO  helper.PluggableLoader  - Trying to load pluggables from jar file: 'test_2.12-0.1.jar'
[error] (run-main-0) java.lang.NoClassDefFoundError: org/codeoverflow/chatoverflow/api/plugin/Pluggable
[error] java.lang.NoClassDefFoundError: org/codeoverflow/chatoverflow/api/plugin/Pluggable
[error]         at java.lang.ClassLoader.defineClass1(Native Method)
[error]         at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
[error]         at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
[error]         at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
[error]         at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
[error]         at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
[error]         at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
[error]         at java.security.AccessController.doPrivileged(Native Method)
[error]         at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
[error]         at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[error]         at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[error]         at org.codeoverflow.chatoverflow.framework.helper.PluggableLoader.findPluggables(PluggableLoader.scala:53)
[error]         at org.codeoverflow.chatoverflow.framework.helper.PluggableLoader.loadPluggables(PluggableLoader.scala:23)
[error]         at org.codeoverflow.chatoverflow.framework.PluginFramework.$anonfun$loadNewPlugins$2(PluginFramework.scala:78)
[error]         at org.codeoverflow.chatoverflow.framework.PluginFramework.$anonfun$loadNewPlugins$2$adapted(PluginFramework.scala:75)
[error]         at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:32)
[error]         at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:29)
[error]         at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:191)
[error]         at org.codeoverflow.chatoverflow.framework.PluginFramework.loadNewPlugins(PluginFramework.scala:75)
[error]         at org.codeoverflow.chatoverflow.ChatOverflow.init(ChatOverflow.scala:62)
[error]         at org.codeoverflow.chatoverflow.Launcher$.$anonfun$main$1(Launcher.scala:35)
[error]         at org.codeoverflow.chatoverflow.Launcher$.$anonfun$main$1$adapted(Launcher.scala:21)
[error]         at org.codeoverflow.chatoverflow.ui.CLI$.parse(CLI.scala:67)
[error]         at org.codeoverflow.chatoverflow.Launcher$.main(Launcher.scala:21)
[error]         at org.codeoverflow.chatoverflow.Launcher.main(Launcher.scala)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]         at java.lang.reflect.Method.invoke(Method.java:498)
[error]         at sbt.Run.invokeMain(Run.scala:93)
[error]         at sbt.Run.run0(Run.scala:87)
[error]         at sbt.Run.execute$1(Run.scala:65)
[error]         at sbt.Run.$anonfun$run$4(Run.scala:77)
[error]         at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error]         at sbt.util.InterfaceUtil$$anon$1.get(InterfaceUtil.scala:10)
[error]         at sbt.TrapExit$App.run(TrapExit.scala:252)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] Caused by: java.lang.ClassNotFoundException: org.codeoverflow.chatoverflow.api.plugin.Pluggable
[error]         at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
[error]         at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[error]         at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[error]         at java.lang.ClassLoader.defineClass1(Native Method)
[error]         at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
[error]         at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
[error]         at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
[error]         at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
[error]         at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
[error]         at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
[error]         at java.security.AccessController.doPrivileged(Native Method)
[error]         at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
[error]         at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[error]         at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[error]         at org.codeoverflow.chatoverflow.framework.helper.PluggableLoader.findPluggables(PluggableLoader.scala:53)
[error]         at org.codeoverflow.chatoverflow.framework.helper.PluggableLoader.loadPluggables(PluggableLoader.scala:23)
[error]         at org.codeoverflow.chatoverflow.framework.PluginFramework.$anonfun$loadNewPlugins$2(PluginFramework.scala:78)
[error]         at org.codeoverflow.chatoverflow.framework.PluginFramework.$anonfun$loadNewPlugins$2$adapted(PluginFramework.scala:75)
[error]         at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:32)
[error]         at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:29)
[error]         at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:191)
[error]         at org.codeoverflow.chatoverflow.framework.PluginFramework.loadNewPlugins(PluginFramework.scala:75)
[error]         at org.codeoverflow.chatoverflow.ChatOverflow.init(ChatOverflow.scala:62)
[error]         at org.codeoverflow.chatoverflow.Launcher$.$anonfun$main$1(Launcher.scala:35)
[error]         at org.codeoverflow.chatoverflow.Launcher$.$anonfun$main$1$adapted(Launcher.scala:21)
[error]         at org.codeoverflow.chatoverflow.ui.CLI$.parse(CLI.scala:67)
[error]         at org.codeoverflow.chatoverflow.Launcher$.main(Launcher.scala:21)
[error]         at org.codeoverflow.chatoverflow.Launcher.main(Launcher.scala)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]         at java.lang.reflect.Method.invoke(Method.java:498)
[error]         at sbt.Run.invokeMain(Run.scala:93)
[error]         at sbt.Run.run0(Run.scala:87)
[error]         at sbt.Run.execute$1(Run.scala:65)
[error]         at sbt.Run.$anonfun$run$4(Run.scala:77)
[error]         at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error]         at sbt.util.InterfaceUtil$$anon$1.get(InterfaceUtil.scala:10)
[error]         at sbt.TrapExit$App.run(TrapExit.scala:252)
[error]         at java.lang.Thread.run(Thread.java:748)
```

**Comment by sebinside** [comment] 2019-08-09 21:11
From this point its not clear, where the problem is. Could be the build environment, code or usage. 

Please come to the code overflow discord an post your problem in the `#help-wanted` channel, they will help you!

**Comment by hlxid** [comment] 2019-08-09 21:25
On `develop` the error message is a bit different:
```
[info] Running org.codeoverflow.chatoverflow.Launcher 
0    23:17:22.384 [run-main-0] INFO  chatoverflow.ChatOverflow  - Minzig!
1    23:17:22.385 [run-main-0] DEBUG chatoverflow.ChatOverflow  - Starting Chat Overflow Framework. API Version is '3.0'. For more information and updates, please visit: http://codeoverflow.org
1    23:17:22.385 [run-main-0] DEBUG chatoverflow.ChatOverflow  - Initialization started.
1    23:17:22.385 [run-main-0] DEBUG chatoverflow.ChatOverflow  - Ensuring that all required directories exist.
3    23:17:22.387 [run-main-0] DEBUG chatoverflow.ChatOverflow  - Enabling framework security policy.
4    23:17:22.388 [run-main-0] DEBUG chatoverflow.ChatOverflow  - Starting plugin framework.
[error] (run-main-0) java.security.AccessControlException: access denied ("java.io.FilePermission" "plugins" "read")
[error] java.security.AccessControlException: access denied ("java.io.FilePermission" "plugins" "read")
[error] 	at java.base/java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
[error] 	at java.base/java.security.AccessController.checkPermission(AccessController.java:895)
[error] 	at java.base/java.lang.SecurityManager.checkPermission(SecurityManager.java:322)
[error] 	at java.base/java.lang.SecurityManager.checkRead(SecurityManager.java:661)
[error] 	at java.base/java.io.File.exists(File.java:815)
[error] 	at org.codeoverflow.chatoverflow.framework.PluginFramework.loadNewPlugins(PluginFramework.scala:65)
[error] 	at org.codeoverflow.chatoverflow.ChatOverflow.init(ChatOverflow.scala:60)
[error] 	at org.codeoverflow.chatoverflow.Launcher$.$anonfun$main$1(Launcher.scala:53)
[error] 	at org.codeoverflow.chatoverflow.Launcher$.$anonfun$main$1$adapted(Launcher.scala:24)
[error] 	at org.codeoverflow.chatoverflow.ui.CLI$.parse(CLI.scala:58)
[error] 	at org.codeoverflow.chatoverflow.Launcher$.main(Launcher.scala:24)
[error] 	at org.codeoverflow.chatoverflow.Launcher.main(Launcher.scala)
[error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[error] 	at sbt.Run.invokeMain(Run.scala:93)
[error] 	at sbt.Run.run0(Run.scala:87)
[error] 	at sbt.Run.execute$1(Run.scala:65)
[error] 	at sbt.Run.$anonfun$run$4(Run.scala:77)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error] 	at sbt.util.InterfaceUtil$$anon$1.get(InterfaceUtil.scala:10)
[error] 	at sbt.TrapExit$App.run(TrapExit.scala:252)
[error] 	at java.base/java.lang.Thread.run(Thread.java:834)
[error] java.lang.RuntimeException: Nonzero exit code: 1
[error] 	at sbt.Run$.executeTrapExit(Run.scala:124)
[error] 	at sbt.Run.run(Run.scala:77)
[error] 	at sbt.Defaults$.$anonfun$bgRunTask$5(Defaults.scala:1172)
[error] 	at sbt.Defaults$.$anonfun$bgRunTask$5$adapted(Defaults.scala:1167)
[error] 	at sbt.internal.BackgroundThreadPool.$anonfun$run$1(DefaultBackgroundJobService.scala:366)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error] 	at scala.util.Try$.apply(Try.scala:209)
[error] 	at sbt.internal.BackgroundThreadPool$BackgroundRunnable.run(DefaultBackgroundJobService.scala:289)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error] 	at java.base/java.lang.Thread.run(Thread.java:834)
[error] (Compile / run) Nonzero exit code: 1
[error] Total time: 15 s, completed Aug 9, 2019, 11:17:22 PM
```
`AccessControlException` hints us to the framework security stuff and if I comment https://github.com/codeoverflow-org/chatoverflow/blob/f2b1f37df77e9087e9332aee76b6cc8be05c1fdd/src/main/scala/org/codeoverflow/chatoverflow/ChatOverflow.scala#L103 then ChatOverflow starts fine inside sbt.

**Comment by hlxid** [comment] 2019-08-10 08:24
Fixed by https://github.com/codeoverflow-org/chatoverflow/commit/053e0061fc156fd0fd5477a44b7fab5d3bef6163

**Closed as completed by hlxid** 2019-08-10 08:24 UTC
Labels: bug
